---
# tasks file for kippo-graph

- name: Kippo-Graph | Insert Apt rule temp 80
  iptables: chain=TCP-OUT protocol=tcp state=present action=insert ctstate=NEW destination_port=80 jump=LOGALLOW
  become: true

- name: Kippo-Graph | Insert Apt rule temp 443
  iptables: chain=TCP-OUT protocol=tcp state=present action=insert ctstate=NEW destination_port=443 jump=LOGALLOW
  become: true

- name: Kippo-Graph | Install dependencies
  apt:
    name: "{{ item }}"
  become: True
  with_items:
    - "{{ kg_apt_dependencies }}"
  notify: Restart Apache

- name: Kippo-Graph | Check if kg cwd exists already
  stat:
    path: "{{ kg_cwd }}"
  register: kg_cwd_exists

- name: Kippo-Graph | Check if kg exists
  stat:
    path: "{{ kg_cwd }}/kippo-graph.php"
  register: kg_exists

- name: Kippo-Graph | Delete kg_cwd
  file:
    state: absent
    path: "{{ cowrie_directory }}"
  when: kg_cwd_exists.stat.exists is defined and kg_cwd_exists.stat.exists
          and kg_exists.stat.exists is defined and kg_exists.stat.exists == False

- name: Kippo-Graph | Clone kg repository
  git:
    repo: https://github.com/ikoniaris/kippo-graph.git
    dest: "{{ kg_cwd }}"
    force: yes
  when: kg_exists.stat.exists is defined and kg_exists.stat.exists == False
  become: True

- name: Kippo-Graph | Set mode for generated-graphs
  file:
    path: "{{ kg_cwd }}"
    owner: "www-data"
    group: "www-data"
    state: directory
    recurse: yes

- name: Kippo-Graph | Set mode for generated-graphs
  file:
    path: "{{ kg_cwd }}/generated-graphs"
    mode: 0777

- name: Kippo-Graph | Drop Apt rule temp 80
  iptables: chain=TCP-OUT protocol=tcp state=absent action=insert ctstate=NEW destination_port=80 jump=LOGALLOW
  become: true

- name: Kippo-Graph | Drop Apt rule temp 443
  iptables: chain=TCP-OUT protocol=tcp state=absent action=insert ctstate=NEW destination_port=443 jump=LOGALLOW
  become: true

- name: Kippo-Graph | Copy configuration file
  template:
    src: config.php.j2
    dest: "{{ kg_cwd }}/config.php"
    group: www-data
    owner: www-data
  become: True

- name: Kippo-Graph | Allow port 80 for Kippo-graph
  iptables: chain=TCP-IN protocol=tcp state=present action=insert ctstate=NEW destination_port=80 jump=LOGALLOW
  become: true
